apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiflow-backend
  labels:
    app: sentiflow-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiflow-backend
  template:
    metadata:
      labels:
        app: sentiflow-backend
    spec:
      containers:
      - name: sentiflow-backend
        image: 525127693154.dkr.ecr.us-east-1.amazonaws.com/sentiflow-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: "sqlite:////tmp/sentiflow.db"
        - name: DATABASE_URL
          value: "sqlite:////tmp/sentiflow.db"