apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiflow-frontend
  labels:
    app: sentiflow-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiflow-frontend
  template:
    metadata:
      labels:
        app: sentiflow-frontend
    spec:
      containers:
      - name: sentiflow-frontend
        image: 525127693154.dkr.ecr.us-east-1.amazonaws.com/sentiflow-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80